### ISSUE TITLE
TTGO_Simple_Test.ino

### ISSUE THREAD

**Issue by caflorin** [inventrdotio/AdventureKit2#11]
We can delete line 4  " The display pins has hard coded to bypass the user_setup.h requirements. "  That was from an earlier run, but I decided it was better to ensure the users properly configured the 2 setup files.   In addition, it is just plain bad English.   Good job cleaning up the code.

**Comment by inetdavid** [comment]
Note that I clarified the buttons by changing 1/2 with left/right and validated that the correct TFT_eSPI config has been set for the T-Display.  Deleted line 4.
