### ISSUE TITLE
AdventureKit2/Getting_Started/Arduino_Mega_2560_R3/140-RealTimeClock Enhancement

### ISSUE THREAD

**Issue by caflorin** [inventrdotio/AdventureKit2#5]
The format for entering current time is not well defined.  Specific issue was with DoW (w).  Recommend adding instructions.  Recommended language follows:

Clock is set from the Serial monitor by entering the current time in the message input line using the below format:

Format of input    YYMMDDwHHMMSS (all digits are numeric and all 13 digits are required)
i.e        2301146130145  

The clock will update and the serial printout will be:

2023/01/14 13:14:45

YY last 2 digets of year
MM month (01 - 12)
DD day   (01-31)
w (from DS3231 library)  (Accepts values of 1 - 7)
HH  Enter 24 hour clock time  (01 - 24)
MM  (00 - 59)
SS  (00 - 59)

**Comment by inetdavid** [comment]
Added some prints at the beginning of the program to document the expected format.
